image := "docker-registry.test-kubernetes/hello-world"
version := "0.0.1"

run:
    dotnet run -C release

docker-build:
    docker build -t {{image}}:{{version}} .

docker-push: docker-build
    docker push {{image}}:{{version}}

run-docker: docker-build
    docker run -it --rm -p 5050:5000 -e ASPNETCORE_URLS=http://*:5000 {{image}}:{{version}}