# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = [
  "control-plane-master",
  #"control-plane-red", "control-plane-blue", 
  "worker-node-red", 
  #"worker-node-blue",
]


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic-x64/ubuntu2204"
  config.vm.box_version = "4.3.12"

  config.vm.provider :libvirt do |libvirt|
    # Enable forwarding of forwarded_port with id 'ssh'.
    libvirt.forward_ssh_port = true
    libvirt.graphics_type = "none"
    libvirt.memory = 2048
  end

  cluster_name = ENV["CLUSTER_NAME"]

  vms.each do |hostname|
    config.vm.define hostname do |node|
      node.vm.hostname = hostname
      
      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if hostname == vms.last
        node.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit = "all"
          ansible.playbook = "../../ansible/kubernetes_playbook.yaml"
          ansible.extra_vars = {
            "cluster_name": cluster_name,
            "username": ENV["USERNAME"],
          }
        end
      end
    end
  end
  
end
