# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = {
  "control-plane-master" => "172.16.122.10",
  #"control-plane-red" : "172.16.122.11",
  #"control-plane-blue" : "172.16.122.12",
  "worker-node-red" => "172.16.122.13",
  #"worker-node-blue" : "172.16.122.14",
}

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream9"
  config.vm.box_version = "20241216.0"

  config.vm.provider :libvirt do |libvirt|
    # Enable forwarding of forwarded_port with id 'ssh'.
    libvirt.forward_ssh_port = true
    libvirt.graphics_type = "none"
    libvirt.cpus = 2
    libvirt.memory = 2048
  end

  cluster_name = ENV["CLUSTER_NAME"]

  network = "vagrant-kube-libvirt"
  host_ip = "172.16.122.5"

  default_network = "vagrant-libvirt"

  counter = 0

  vms.each do |hostname, ip|
    config.vm.define hostname do |node|
      node.vm.hostname = hostname

      node.vm.network :private_network,
        :ip => ip,
        :libvirt__netmask => '255.255.255.0',
        :libvirt__network_name => network,
        :libvirt__dhcp_enabled => false,
        :libvirt__host_ip => host_ip,
        :libvirt__guest_ipv6 => false

      counter += 1
      
      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if counter == vms.length
        node.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit = "all"
          ansible.playbook = "../../ansible/kubernetes_playbook.yaml"
          ansible.extra_vars = {
            "cluster_name": cluster_name,
            "username": ENV["USERNAME"],
            "machines": vms,
          }
          #ansible.verbose = "vv"
        end
      end
    end
  end
  
end
