install:
    terraform init 

plan:
    terraform plan

apply key_file_path cert_file_path: install
    #!/usr/bin/env bash
    terraform apply --auto-approve \
    -var "key_file_path={{key_file_path}}" \
    -var "cert_file_path={{cert_file_path}}"

destroy: install
    terraform destroy

lint:
    docker run --rm -v $(pwd):/data -t ghcr.io/terraform-linters/tflint --recursive --minimum-failure-severity=warning

clean:
    rm -rf .terraform
    rm -rf .terraform.lock.hcl
    rm -rf terraform.tfstate
    rm -rf terraform.tfstate.backup