apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-config
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx</title>
    </head>
    <body>
        <h1>Hello, Kubernetes!</h1>
        <p>This is a static page served by Nginx using a ConfigMap.</p>
    </body>
    </html>
