---
- name: Check OS version
  ansible.builtin.fail:
    msg: "OS should be Ubuntu 22.04, not {{ ansible_distribution }} {{ ansible_distribution_version }}"
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '22.04'

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Disable SWAP in fstab (Kubeadm requirement)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  changed_when: ansible_swaptotal_mb == 0

- name: Disable SWAP (Kubeadm requirement)
  ansible.builtin.command:
    cmd: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: ansible_swaptotal_mb == 0

- name: Configure modules for Containerd
  ansible.builtin.copy:
    src: etc/modules-load.d/containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    mode: "0644"

# Required to call Set bridge-nf-call-iptables
- name: Load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set bridge-nf-call-iptables
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: Set ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Reboot and wait for reboot to complete
  ansible.builtin.reboot:
  when: ansible_facts['services']['containerd']['status'] | default('not-found') == 'not-found'
