---
- name: Check OS version
  ansible.builtin.fail:
    msg: "OS should be Centos 9, not {{ ansible_distribution }} {{ ansible_distribution_version }}"
  when: ansible_distribution != 'CentOS' or ansible_distribution_version != '9'

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Write noswap systemd unit file
  ansible.builtin.template:
    src: etc/systemd/system/noswap.service.j2
    dest: /etc/systemd/system/noswap.service
    owner: root
    group: root
    mode: "0644"

- name: Enable noswap service
  ansible.builtin.systemd:
    name: noswap
    state: started
    enabled: true
    daemon_reload: true

- name: Disable SWAP (Kubeadm requirement)
  ansible.builtin.command:
    cmd: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: ansible_swaptotal_mb == 0

- name: Configure modules for Containerd
  ansible.builtin.copy:
    src: etc/modules-load.d/containerd.conf
    dest: /etc/modules-load.d/containerd.conf
    mode: "0644"

# Required to call Set bridge-nf-call-iptables
- name: Load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set bridge-nf-call-iptables
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: Set ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: Reboot and wait for reboot to complete
  ansible.builtin.reboot:
  when: ansible_facts['services']['containerd']['status'] | default('not-found') == 'not-found'
