---
- name: Add repo for Docker
  ansible.builtin.copy:
    src: etc/yum.repos.d/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: "0644"

- name: Install Containerd
  ansible.builtin.dnf:
    name: containerd.io
    state: present
    update_cache: true

- name: Create Containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Configuring Containerd
  ansible.builtin.copy:
    src: etc/containerd/config.toml
    dest: /etc/containerd/config.toml
    mode: "0755"

- name: Enable the Containerd service and start it
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon-reload: true

- name: Add repo for Kubernetes
  ansible.builtin.template:
    src: etc/yum.repos.d/kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: "0644"

- name: Install Kubeadm
  ansible.builtin.dnf:
    name: "kubeadm"
    state: present
    update_cache: true

- name: Install Kubelet
  ansible.builtin.dnf:
    name: "kubelet"
    state: present
