- name: Grow the partition
  ansible.builtin.import_tasks: ./grow_partition.yaml
- name: Configure linux
  ansible.builtin.import_tasks: ./configure_linux.yaml
- name: Install CA
  ansible.builtin.import_tasks: ./install_ca.yaml
- name: Install dependencies
  ansible.builtin.import_tasks: ./install_dependencies.yaml
- name: Setup hosts
  ansible.builtin.import_tasks: ./setup_hosts.yaml
- name: Enable the Kubelet service, and enable it persistently
  ansible.builtin.service:
    name: kubelet
    enabled: true
