fmt:
    terragrunt hclfmt
    terragrunt run-all fmt

init:
    terragrunt run-all init

refresh: init
    terragrunt run-all refresh

# prepend TF_LOG=INFO to see the logs
apply: init
    TF_LOG=INFO terragrunt run-all apply

destroy:
    TF_LOG=INFO terragrunt run-all destroy

clean:
    terragrunt --terragrunt-working-dir ./k8s-cluster destroy
    find . -type d -name ".terragrunt-cache" -prune -exec /bin/rm -v -rf '{}' \;
    find . -name ".terraform.lock.hcl" -exec /bin/rm -v '{}' \;
    

print-sensitive module sensitive:
    @terragrunt output --terragrunt-working-dir {{module}} {{sensitive}}