install:
    terraform init 

plan:
    terraform plan

apply cluster_master_ip cluster_worker_node ca_key_file_path ca_cert_file_path kubeconfig_file_path nfs_server: install
    #!/usr/bin/env bash
    terraform apply --auto-approve \
    -var "cluster_master_ip={{cluster_master_ip}}" \
    -var "cluster_worker_node={{cluster_worker_node}}" \
    -var "ca_key_file_path={{ca_key_file_path}}" \
    -var "ca_cert_file_path={{ca_cert_file_path}}" \
    -var "kubeconfig_file_path={{kubeconfig_file_path}}" \
    -var "nfs_server={{nfs_server}}"

destroy: install
    terraform destroy

lint:
    docker run --rm -v $(pwd):/data -t ghcr.io/terraform-linters/tflint --recursive --minimum-failure-severity=warning

clean:
    rm -rf .terraform
    rm -rf .terraform.lock.hcl
    rm -rf terraform.tfstate
    rm -rf terraform.tfstate.backup