install:
    terraform init 

plan:
    terraform plan

apply: install
    terraform apply --auto-approve

destroy: install
    terraform destroy

clean:
    rm -rf .terraform
    rm -rf .terraform.lock.hcl
    rm -rf terraform.tfstate
    rm -rf terraform.tfstate.backup