lint: lint-day-one lint-test-kubernetes-ca

lint-day-one:
    just day-one/lint

lint-test-kubernetes-ca:
    just test-kubernetes-ca/lint

day-one cluster_master_ip ca_key_file_path ca_cert_file_path kubeconfig_file_path nfs_server:
    just day-one/apply {{cluster_master_ip}} {{ca_key_file_path}} {{ca_cert_file_path}} {{kubeconfig_file_path}} {{nfs_server}}

test_kubernetes_ca key_file_path cert_file_path:
    just test-kubernetes-ca/apply {{key_file_path}} {{cert_file_path}}

destroy:
    just day-one/destroy

clean:
    just day-one/clean