# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: docker.io/pihole/pihole
  pullPolicy: Always
  tag: "2024.07.0"

web_password_secret_name: ""

service:
  containerPort: 5000
  allowSharedIp: "nginx"

ingress:
  host: pi-hole.test-kubernetes
  certIssuer: selfsigned-cluster-issuer
