- name: TCP port 6443 on master is reachable from worker
  ansible.builtin.wait_for:
    host: "{{ machines['control-plane-master']['ip'] }}"
    port: 6443
    timeout: 60
    delay: 1

- name: Generate join config
  ansible.builtin.template:
    src: etc/kubernetes/join.j2.yaml
    dest: /etc/kubernetes/join.yaml
    mode: "0755"
    owner: root
    group: root
  vars:
    control_plane_endpoint: "{{ machines['control-plane-master']['ip'] }}:6443"
    kube_adm_token: "{{ hostvars['control-plane-master']['worker_join_token'] }}"
    discovery_token_ca_cert_hash: "{{ hostvars['control-plane-master']['discovery_token_ca_cert_hash'] }}"
    advertise_address: "{{ machines[inventory_hostname]['ip'] }}"

- name: Join cluster
  ansible.builtin.shell: kubeadm join --config /etc/kubernetes/join.yaml > join.log
  args:
    chdir: /home/vagrant
    creates: join.log

- name: Fetch join.log
  ansible.builtin.fetch:
    src: /home/vagrant/join.log
    dest: ./fetched
    force: true
