- name: Add Helm apt-key
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /etc/apt/keyrings/helm-apt-keyring.asc
    mode: "0644"
    force: true

- name: Add Helms's APT repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}
      signed-by=/etc/apt/keyrings/helm-apt-keyring.asc]
      https://baltocdn.com/helm/stable/debian/ all main
    state: present
    update_cache: true

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present
    update_cache: true

- name: Install python3-kubernetes
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
    update_cache: true

# Needs manual creation of namespace to avoid helm error
- name: Create kube-flannel namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconf }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-flannel
        labels:
          pod-security.kubernetes.io/enforce: privileged

- name: Add chart repo for flannel
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: "https://flannel-io.github.io/flannel/"

- name: Deploy flannel chart
  kubernetes.core.helm:
    name: flannel
    kubeconfig: "{{ kubeconf }}"
    chart_ref: flannel/flannel
    release_namespace: kube-flannel
    create_namespace: false
    values:
      flannel:
        backend: "host-gw"
