apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ca_secret_name }}
  namespace: {{ .Release.namespace }}
data:
  tls.crt: {{ .Values.ca_cert.tls_crt | b64enc }}
  tls.key: {{ .Values.ca_cert.tls_key | b64enc }}