# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: docker-registry.test-kubernetes/hello-world
  pullPolicy: Always
  tag: "0.0.1"

serviceAccount:
  name: ""

service:
  containerPort: 5000

ingress:
  host: hello-world.test-kubernetes
  certIssuer: selfsigned-cluster-issuer
  pathRegEx: "/helloworld(/|$)(.*)"
