- name: Day One Playbook
  hosts: localhost
  connection: local
  vars:
    kubeconfig: fetched/control-plane/etc/kubernetes/admin.conf
  tasks:

    - name: Add chart repo for nginx-ingress
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Deploy ingress-nginx chart
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        kubeconfig: '{{ kubeconfig }}'
        values:
          controller:
            kind: daemonset
