- name: Control Plane Playbook
  hosts: control-plane
  become: true
  roles:
    - kube-node
    - control-plane
    - helm-bootstrapper
    - flannel-networking
- name: Worker node Playbook
  hosts:
    - worker-node-red
    - worker-node-blue
  become: true
  roles:
    - kube-node
    - worker-node
