- name: Control Plane Playbook
  hosts: control-plane
  become: true
  roles:
    - kube_node
    - control_plane
    - helm_bootstrapper
    - flannel_networking
- name: Worker node Playbook
  hosts:
    - worker-node-red
    - worker-node-blue
  become: true
  roles:
    - kube_node
    - worker_node
