- name: Setup common configuration for kube node
  hosts:
    - control-plane-master
    - control-plane-red
    - control-plane-blue
    - worker-node-red
    - worker-node-blue
  become: true
  roles:
    - kube_node
  vars_files:
    - vars/main.yaml

- name: Setup control plane master
  hosts: control-plane-master
  become: true
  roles:
    - control_plane_master
    - admin_user_bootstrapper
  vars_files:
    - vars/main.yaml

- name: Setup control plane nodes
  hosts:
    - control-plane-red
    - control-plane-blue
  become: true
  roles:
    - control_plane_node
  vars_files:
    - vars/main.yaml

- name: Setup worker nodes
  hosts:
    - worker-node-red
    - worker-node-blue
  become: true
  roles:
    - worker_node
  vars_files:
    - vars/main.yaml
