- name: Networking Playbook
  hosts: localhost
  connection: local
  vars:
    kubeconfig: fetched/control-plane/etc/kubernetes/admin.conf
  tasks:
    # Needs manual creation of namespace to avoid helm error
    - name: Create kube-flannel namespace
      kubernetes.core.k8s:
        state: present
        kubeconfig: '{{ kubeconfig }}'
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: kube-flannel
            labels:
              pod-security.kubernetes.io/enforce: privileged

    - name: Add chart repo for flannel
      kubernetes.core.helm_repository:
        name: flannel
        repo_url: "https://flannel-io.github.io/flannel/"

    - name: Deploy flannel chart
      kubernetes.core.helm:
        name: flannel
        chart_ref: flannel/flannel
        release_namespace: kube-flannel
        create_namespace: false
        kubeconfig: '{{ kubeconfig }}'
