apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.address_pool_name }}
  namespace: {{ .Release.namespace }}
spec:
  addresses:
  {{- range .Values.ips }}
  - {{ . }}/32
  {{- end }}