apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-webhook
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
