- name: Install Kubelet
  ansible.builtin.apt:
    name: kubelet={{ kube_version }}.*
    state: present
    update_cache: true

- name: Enable the Kubelet service, and enable it persistently
  ansible.builtin.service:
    name: kubelet
    enabled: true

- name: Create an empty file for Kubeadm configuring
  ansible.builtin.copy:
    content: ""
    dest: /etc/kubernetes/kubeadm-config.yaml
    force: false
    mode: '0644'
    owner: root
    group: root

- name: Configuring kubelet
  ansible.builtin.template:
    src: etc/kubernetes/kubeadm-config.j2.yaml
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: "0755"
    owner: root
    group: root

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Initialize the cluster (this could take some time)
  ansible.builtin.shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml > cluster_initialized.log
  args:
    chdir: /home/vagrant
    creates: cluster_initialized.log
  when: ansible_facts['services']['kubelet']['status'] | default('not-found') != 'active'

- name: Fetch cluster_initialized.log
  ansible.builtin.fetch:
    src: /home/vagrant/cluster_initialized.log
    dest: ./fetched
    force: true

- name: Fetch kube config
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./fetched
    force: true

- name: Get CA certificate hash
  community.crypto.x509_certificate_info:
    path: /etc/kubernetes/pki/ca.crt
  register: k8s_pki_ca

- name: Set fact for join command
  ansible.builtin.set_fact:
    discovery_token_ca_cert_hash: sha256:{{ k8s_pki_ca["public_key_fingerprints"]["sha256"] | replace(":", "") }}

- name: Create join token for worker-node
  ansible.builtin.command: kubeadm token create
  register: join_command
  changed_when: false

- name: Set fact for join command
  ansible.builtin.set_fact:
    join_token: "{{ join_command.stdout }}"
